#!/bin/bash

set -e

echo "initializing CPSESSION..."
iptables -F CPSESSION
iptables -A CPSESSION -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A CPSESSION -p tcp --dport 53 -j ACCEPT
iptables -A CPSESSION -p udp --dport 53 -j ACCEPT

iptables -t nat -F CPSESSION
echo "done."
