#! /bin/sh

do_start() {
  echo "Starting ucaptive..."
  ( /root/ucaptive/server >>/var/log/ucaptive.log 2>>/var/log/ucaptive.err ) &
  sleep 2
  ps aux | grep python.*ucaptive.*server | grep -v grep
}

do_stop() {
  echo "Stopping ucaptive..."
  ps aux | grep python.*ucaptive.*server | grep -v grep | awk '{print $2}' | xargs kill -9 2>/dev/null
}

if [ "$1" = "start" ]; then
  do_start
fi

if [ "$1" = "stop" ]; then
  do_stop
fi

if [ "$1" = "restart" ]; then
  do_stop
  sleep 3
  do_start
fi

